name: Build DXCam Version
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # DXCam is required for this version
          pip install dxcam numpy keyboard pynput pywin32 Pillow requests

      - name: Build with PyInstaller
        # We name the .exe "KarooFishDX" (No spaces) to prevent command line errors
        run: pyinstaller --onefile --noconsole --uac-admin --collect-all dxcam --name KarooFishDX fishyfish.py

      - uses: actions/upload-artifact@v4
        with:
          # The name of the download button on GitHub
          name: Karoo Fish - DX
          # The path to the file PyInstaller just made (Must match the --name above)
          path: dist/KarooFishDX.exe
